version: "3.8"

services:
  db:
    image: postgres:12-alpine
    container_name: skeleton_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skeleton
      POSTGRES_PASSWORD: "111111"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - skeleton
    restart: always
  redis:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - skeleton
    restart: always
volumes:
  postgres:

networks:
  skeleton:
    name: skeleton
    driver: bridge
